name: Build and Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: out/make/squirrel.windows/x64/test-electron-publish-1.0.0\ Setup.exe
